// Format a number as Sri Lankan Rupees with thousand separators
export function formatLKR(n) {
  if (n === null || n === undefined || isNaN(n)) return "0";
  return Number(n).toLocaleString("en-LK", { maximumFractionDigits: 0 });
}

export function formatNumber(n, decimals = 2) {
  if (n === null || n === undefined || isNaN(n)) return "0";
  return Number(n).toLocaleString("en-LK", {
    minimumFractionDigits: 0,
    maximumFractionDigits: decimals,
  });
}

// Bill of Quantities builder
export function buildBOQ(project, estimate) {
  const now = new Date();
  const calcDate = estimate?.calculatedAt
    ? new Date(estimate.calculatedAt)
    : now;

  // Header info
  const projectName = project?.name || "Untitled Project";
  const region = estimate?.settingsUsed?.region || "western";

  // Summary metrics
  const summary = [
    { label: "Project Name", value: projectName, unit: "" },
    { label: "Calculated On", value: calcDate.toLocaleString(), unit: "" },
    {
      label: "Region",
      value: region.charAt(0).toUpperCase() + region.slice(1),
      unit: "Province",
    },
    {
      label: "Total Floor Area",
      value: formatNumber(estimate?.totalFloorArea, 2),
      unit: "m²",
    },
    {
      label: "Total Wall Length",
      value: formatNumber(estimate?.totalWallLength, 2),
      unit: "m",
    },
    {
      label: "Total Wall Area",
      value: formatNumber(estimate?.totalWallArea, 2),
      unit: "m²",
    },
    {
      label: "Estimated Duration",
      value: estimate?.estimatedDays || 0,
      unit: "days",
    },
  ];

  // Room schedule
  const rooms = (project?.rooms || []).map((r, i) => ({
    no: i + 1,
    name: r.name || `Room ${i + 1}`,
    type: (r.type || "other").toLowerCase(),
    area: Number(r.area || 0),
    perimeter: Number(r.perimeter || 0),
  }));

  // Materials
  const materialItems = (estimate?.materials || []).map((m, i) => ({
    no: i + 1,
    item: m.item,
    quantity: Number(m.quantity || 0),
    unit: m.unit,
    rate: Number(m.rate || 0),
    wastage: Number(m.wastage || 0),
    total: Number(m.total || 0),
  }));
  const materialSubtotal = materialItems.reduce((s, m) => s + m.total, 0);

  // Labour
  const labourItems = (estimate?.labour || []).map((l, i) => ({
    no: i + 1,
    task: l.task,
    days: Number(l.days || 0),
    workers: Number(l.workers || 0),
    rate: Number(l.rate || 0),
    total: Number(l.total || 0),
  }));
  const labourSubtotal = labourItems.reduce((s, l) => s + l.total, 0);

  // Grand total
  const grandTotal = materialSubtotal + labourSubtotal;

  // Notes
  const notes = [
    `Wastage applied: ${estimate?.settingsUsed?.includeWastage ? "Yes" : "No"}`,
    "Material rates and labour productivity based on ICTAD Schedule of Rates norms.",
    "This estimate is indicative only. Final costs may vary based on site conditions, transport, and market fluctuations.",
    `Document generated by Quantrox on ${now.toLocaleString()}.`,
  ];

  return {
    title: "BILL OF QUANTITIES",
    projectName,
    generatedAt: now,
    calcDate,
    summary,
    rooms,
    materials: {
      items: materialItems,
      subtotal: materialSubtotal,
    },
    labour: {
      items: labourItems,
      subtotal: labourSubtotal,
    },
    grandTotal,
    notes,
    meta: {
      region,
      includeWastage: estimate?.settingsUsed?.includeWastage,
      wastageFactors: estimate?.settingsUsed?.wastageFactors,
      materialRates: estimate?.settingsUsed?.materialRates,
      labourRates: estimate?.settingsUsed?.labourRates,
    },
  };
}

//  Helper: produce a safe download filename
export function buildFilename(projectName, ext) {
  const safe = (projectName || "Quantrox-BOQ")
    .replace(/[^\w\d\s\-]/g, "")
    .replace(/\s+/g, "_") 
    .substring(0, 60); 
  const date = new Date().toISOString().split("T")[0];
  return `${safe}_BOQ_${date}.${ext}`;
}
